version: '3'

services:
  mysql:
   container_name: mysql
   environment:
      MYSQL_ROOT_PASSWORD: "root123456"
      MYSQL_DATABASE: homework
   image:  "mysql:8.0.21"
   restart: always
   volumes:
        - "./data/mysql/data:/var/lib/mysql"
        - "./data/mysql/conf/my.cnf:/etc/my.cnf"
   ports:
        - "3306:3306"
   command: --default-authentication-plugin=mysql_native_password
  web:
    container_name: web
    build: django
    restart: always
    depends_on:
      - mysql
    links:
      - "mysql:mysql"
    privileged: true
    ports:
      - "8000:8000"
    command:  sh /sh/wait-for-it.sh mysql:3306 -s -t 3600 -- sh /sh/web.sh
    volumes:
      - ./django/code:/code
  nginx:
    container_name: nginx
    depends_on:
      - web
    links:
      - "web:web"
    restart: always
    build: nginx
    ports:
      - "80:80"
    volumes:
      - ./data/nginx/data:/var/log/nginx
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/dist:/dist


